AMGamtrs/curreach

- app/Http/routes.php
> #49 ルーティングの追加

- app/Http/Controllers/CurreachsController.php
- app/Http/Controllers/CurrysController.php
- app/Http/Controllers/ShopsController.php
> #50 コントローラの作成(雛形)

- app/Http/Controllers/CurreachsController.php
- app/Http/Controllers/CurrysController.php
- app/Http/Controllers/ShopsController.php
> #50 コントローラの修正

- app/Http/routes.php
> #49 ルーティングの修正

- app/Curry.php
- app/Photo.php
- app/Shop.php
- database/migrations/2018_06_26_032411_create_shops_table.php
- database/migrations/2018_06_26_033340_create_curries_table.php
- database/migrations/2018_06_26_033852_create_photos_table.php
- database/migrations/2018_06_26_035247_add_column_shop_id_curries_table.php
#62 データベースの作成
モデルおよびDBの作成まで
Shop, Curry, Photoモデルを追加
DBへshops, curries, photosテーブルを追加するマイグレーションファイルを追加
アソシエーションを設定
　┗shop hasmany curries
　┗shop hasmany photos
　┗curry hasmany photos
DBを作成し.envを作成後、migrate実行でテーブルが追加されるようになる
> #62 create db

- composer.lock
> composer.lockのアップ

- composer.lock
- resources/views/shops/create.blade.php
> 店舗登録ビューの作成

- composer.json
- composer.lock
- config/app.php
- resources/views/auth/login.blade.php
- resources/views/curries/create.blade.php
- resources/views/layout.blade.php
> #54ログインページビューと#58カレー登録ページビューの作成

- database/seeds/CurryTableSeeder.php
- database/seeds/DatabaseSeeder.php
- database/seeds/ShopTableSeeder.php
#62 
初期の店舗情報の入力
初期のカレー情報の入力
Seederを追加
php artisan db:seed
DBリセットしてシーダの中身をDBに入れる
> テスト用の店舗情報・カレー情報を追加するseeder作成

- composer.json
- composer.lock
- config/app.php
- resources/views/curries/create.blade.php
> #58カレー登録ページにて写真をフォルダから選択できるように変更

- resources/views/auth/register.blade.php
> Hogehoge #59

- app/Http/Controllers/ShopsController.php
- app/Http/routes.php
> mapajaxアクションの追加

- public/css/sticky-footer.css
- resources/views/auth/login.blade.php
- resources/views/layout.blade.php
> ナビバーの調整（ログイン状況によるボタン表示、検索バー右配置）とフッターの実装

- resources/views/curries/show.blade.php
> カレー詳細ビュー（本物）

- app/Http/Controllers/Auth/AuthController.php
- resources/views/auth/register.blade.php
> Implementation of login function

- resources/views/shops/show.blade.php
> 店舗の位置を表示する地図追加

- app/Http/Controllers/UsersController.php
- resources/views/auth/login.blade.php
- resources/views/users/show.blade.php
> マイページビューの作成、UsersControlerの追記

- resources/views/shops/create.blade.php
> #57 addmap

- resources/views/layout.blade.php
> ナビバーの余計なものを削除しました。

- public/css/style.css
- resources/views/curreaches/index.blade.php
- resources/views/layout.blade.php
- resources/views/shops/mapsearch.blade.php
> #61_css_top_update

- app/Curry.php
- app/Photo.php
- app/Review.php
- app/Shop.php
- database/migrations/2018_07_09_094749_create_reviews_table.php
> #105 review table

- resources/views/shops/create.blade.php
- resources/views/shops/mapsearch.blade.php
- resources/views/shops/show.blade.php
> Apiキーを定数にする

- resources/views/shops/mapsearch.blade.php
> 書き忘れ訂正しました

- resources/views/shops/mapsearch.blade.php
> マーカの緯度経度の型変換

- public/css/show.css
- resources/views/curries/show.blade.php
- resources/views/layout.blade.php
> 写真をスライド形式で表示

- public/css/style.css
- resources/views/sidebar.blade.php
> サイドバーをシンプルにしました。

- public/css/style.css
- resources/views/curreaches/index.blade.php
> Add text on images

- app/Http/Controllers/ReviewsController.php
- app/Http/routes.php
- app/Review.php
- app/User.php
- public/css/show.css
- resources/views/curries/show.blade.php
> #113 curry show form

- app/Http/Controllers/CurriesController.php
- app/Http/Controllers/ShopsController.php
- app/Providers/GoogleDriveServiceProvider.php
- composer.json
- composer.lock
- config/app.php
- config/filesystems.php
- database/seeds/PhotoTableSeeder.php
- resources/views/curreaches/index.blade.php
- resources/views/curries/create.blade.php
- resources/views/curries/search.blade.php
> Google drive link

- resources/views/shops/mapsearch.blade.php
> Mapserch addimfo

- composer.json
- composer.lock
> composer.json update

- database/seeds/PhotoTableSeeder.php
> photosの空白データをnullに変更

- app/Http/Controllers/CurriesController.php
- app/User.php
- composer.json
- composer.lock
- database/migrations/2018_07_17_002257_edit_users_table_icon_column.php
- resources/views/curries/create.blade.php
- resources/views/curries/show.blade.php
- resources/views/shops/show.blade.php
> Minor fixes

- database/seeds/ReviewTableSeeder.php
> reviewDBのshopsを10〜20削除しました。。

- app/Http/Controllers/CurriesController.php
- app/Http/Controllers/ShopsController.php
- public/css/style.css
- resources/views/curries/search.blade.php
- resources/views/layout.blade.php
> Create a page for curry registration

- app/Bookmarks.php
- app/Favorites.php
- database/migrations/2018_07_19_104150_create_bookmarks_table.php
- database/migrations/2018_07_19_104413_create_favorites_table.php
- database/migrations/2018_07_19_110947_add_column_regular_holiday_shops_table.php
- database/migrations/2018_07_19_111505_add_column_allergies_curries_table.php
- database/migrations/2018_07_19_113039_rename_main_ingredien_column.php
> add : migration_files  - カラムの変更、追加をしました. -

- resources/views/shops/show.blade.php
> レビューを編集して、写真ラベルと５段階評価にした

- resources/views/shops/show.blade.php
> 円とメニュー追加。競合がこわひ

- public/css/style.css
- resources/views/shops/create.blade.php
> 店舗登録ページの更新

- app/Http/Controllers/CurriesController.php
- resources/views/curries/show.blade.php
> Changed from main_igredien to main_igredient

- public/css/style.css
- resources/views/curries/create.blade.php
> カレー 登録ページの更新

- resources/views/shops/create.blade.php
> 店舗登録ページちょっと修正

- resources/views/curries/show.blade.php
- resources/views/shops/show.blade.php
> 店舗とカレーの詳細ページをペチペチしました。（レイアウト統一）

- resources/views/auth/register.blade.php
> パスワード入力時の注意点追加

- app/Http/Controllers/Auth/AuthController.php
- resources/views/auth/login.blade.php
- resources/views/auth/register.blade.php
> Login controller

- public/css/style.css
- resources/views/curreaches/index.blade.php
> bass_frame

- public/css/style.css
> トップページのサイドバーのデザイン最終バージョン

- resources/views/shops/create.blade.php
- resources/views/shops/show.blade.php
> ＃5 詳細情報数字のものを文字に置換

- app/Http/Controllers/Auth/AuthController.php
- public/css/style.css
- resources/views/layout.blade.php
- resources/views/shops/show.blade.php
- resources/views/users/bookmarks.blade.php
- resources/views/users/likes.blade.php
- resources/views/users/profile.blade.php
- resources/views/users/profileleft.blade.php
- resources/views/users/show.blade.php
> edit mypage

- resources/views/curries/create.blade.php
- resources/views/curries/show.blade.php
> カレー 詳細ページ（詳細情報数字のものを文字に置換）等

- app/Http/Controllers/ShopsController.php
> Herokuのポスグレ用にsql文変更

- resources/views/curries/search.blade.php
- resources/views/sidebar.blade.php
> #173 search

- resources/views/shops/mapsearch.blade.php
> mapserch画像表示修正

- resources/views/curries/show.blade.php
> カレー詳細にいいねボタン追加

- resources/views/shops/mapsearch.blade.php
> 地図検索　初期位置変更
